name: 'Vercel Action'
description: 'This action make a deployment with github actions instead of Vercel builder.'

runs:
  using: composite
  steps:
    - run: bun ${{ github.action_path }}/dist/main.js
      shell: bash

branding:
  icon: 'triangle'
  color: 'white'
